# Documentation at http://goreleaser.com
builds:
  - env: [ CGO_ENABLED=0 ]
    goos: [ linux, darwin ]
    goarch: [ amd64 ]
archives:
    - format: binary
dockers:
  - image_templates:
      - "skpr/cluster-metrics:latest"
      - "skpr/cluster-metrics:{{ .Tag }}"
    build_flag_templates: [ "--pull" ]
release:
  prerelease: auto
  github:
    owner: skpr
    name: cluster-metrics
