# Documentation at http://goreleaser.com
builds:
  - env: [ CGO_ENABLED=0 ]
    goos: [ linux, darwin ]
    goarch: [ amd64 ]
archives:
    - format: binary
    - id: assets
      name_template: >-
        {{- .ProjectName }}_
        {{- .Tag }}_
        {{- if eq .Os "darwin" }}macOS
        {{- else if eq .Os "linux"}}linux{{ end }}_
        {{- if eq .Arch "amd64" }}x86_64
        {{- else if eq .Arch "386" }}i386
        {{- else }}{{ .Arch }}{{ end }}
        {{- if .Arm }}v{{ .Arm }}{{ end -}}
dockers:
  - image_templates:
      - "skpr/cluster-metrics:latest"
      - "skpr/cluster-metrics:{{ .Tag }}"
    build_flag_templates: [ "--pull" ]
release:
  prerelease: auto
  github:
    owner: skpr
    name: cluster-metrics
