version: 2

workflows:
  version: 2
  build:
    jobs:
      - build
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              # Only on tags formatted like v0.1.1
              only: /^v\d+\.\d+\.\d+$/

jobs:
  build:
    docker:
      - image: golang:1.16
    working_directory: /go/src/github.com/skpr/cluster-metrics
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Lint
          command: |
            go get golang.org/x/lint/golint
            make lint
      - run:
          name: Test
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - store_test_results:
          path: /tmp/test-reports

  release:
    docker:
      - image: golang:1.16
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            apt-get update && apt-get install -y zip
            go get github.com/tcnksm/ghr
      - run:
          name: "Build"
          command: make package
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(git describe --tags --always)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./function.zip
