version: 2.1

workflows:
  build:
    jobs:
      - build
  release:
    jobs:
      - release:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              # Only on tags formatted like v0.1.1
              only: /^v\d+\.\d+\.\d+$/

jobs:
  build:
    docker:
      - image: golang:1.17
    working_directory: ~/repo
    environment:
      GO111MODULE: on
    steps:
      - checkout
      - run:
          name: Vet
          command: |
            make vet
      - run:
          name: Lint
          command: |
            go get golang.org/x/lint/golint
            make lint
      - run:
          name: Test
          command: |
            go test ./... -coverprofile cover.out

  release:
    docker:
      - image: docker.io/goreleaser/goreleaser:latest
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: goreleaser
