version: 2

workflows:
  version: 2
  build:
    jobs:
      - build
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              # Only on tags formatted like v0.1.1
              only: /^v\d+\.\d+\.\d+$/

jobs:
  build:
    docker:
      - image: golang:1.16
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Lint
          command: |
            go get golang.org/x/lint/golint
            make lint
      - run:
          name: Test
          command: |
            mkdir -p /tmp/test-reports
            go get gotest.tools/gotestsum
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - store_test_results:
          path: /tmp/test-reports

  release:
    docker:
      - image: docker.io/goreleaser/goreleaser:latest
    working_directory: /go/src/github.com/skpr/cluster-metrics
    steps:
      - checkout
      - setup_remote_docker
      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: goreleaser
